import { StyleSheet, Dimensions, Platform } from 'react-native';

const { width: screenWidth, height: screenHeight } = Dimensions.get('window');

export const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  overlayGradient: {
    ...StyleSheet.absoluteFillObject,
  },
  container: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
  cardContainer: {
    width: Math.min(screenWidth * 0.85, 360),
    height: Math.min(screenHeight * 0.65, 520),
    position: 'relative',
    justifyContent: 'center',
    alignItems: 'center',
  },
  cardShadowLayerOuter: {
    position: 'absolute',
    width: '96%',
    height: '96%',
    borderRadius: 30,
    backgroundColor: 'rgba(2,6,23,0.58)',
    transform: [{ translateY: 22 }, { scaleX: 0.93 }],
    ...Platform.select({
      ios: {
        shadowColor: '#020617',
        shadowOffset: { width: 0, height: 30 },
        shadowOpacity: 0.66,
        shadowRadius: 24,
      },
      android: {
        elevation: 16,
      },
    }),
  },
  cardShadowLayerInner: {
    position: 'absolute',
    width: '92%',
    height: '93%',
    borderRadius: 28,
    backgroundColor: 'rgba(30,41,59,0.44)',
    transform: [{ translateY: 13 }, { scaleX: 0.96 }],
  },
  card: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    backfaceVisibility: 'hidden',
    borderRadius: 28,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(15,23,42,0.12)',
    ...Platform.select({
      ios: {
        shadowColor: '#0f172a',
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.24,
        shadowRadius: 18,
      },
      android: {
        elevation: 12,
      },
    }),
  },
  cardBack: {
    zIndex: 2,
  },
  cardFront: {
    zIndex: 1,
  },
  cardDepthTop: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: '34%',
  },
  cardDepthBottom: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: '38%',
  },
  cardBackGradient: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  cardBackFrameOuter: {
    position: 'absolute',
    top: 10,
    right: 10,
    bottom: 10,
    left: 10,
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: 'rgba(255,255,255,0.22)',
  },
  cardBackFrameInner: {
    position: 'absolute',
    top: 22,
    right: 22,
    bottom: 22,
    left: 22,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.14)',
  },
  cardBackBadge: {
    width: 96,
    height: 96,
    borderRadius: 48,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.14)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.24)',
    marginBottom: 18,
  },
  cardBackIcon: {
    width: 44,
    height: 44,
    tintColor: '#FFFFFF',
  },
  cardBackText: {
    fontSize: 28,
    fontWeight: '800',
    color: '#FFFFFF',
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  cardBackSubText: {
    fontSize: 13,
    fontWeight: '600',
    color: 'rgba(255,255,255,0.86)',
    marginTop: 10,
    letterSpacing: 0.4,
  },
  cardBackPattern: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    opacity: 0.12,
  },
  patternCircle: {
    position: 'absolute',
    borderWidth: 1.5,
    borderColor: '#FFFFFF',
  },
  backPatternRing: {
    backgroundColor: 'transparent',
  },
  backPatternSquare: {
    backgroundColor: 'rgba(255,255,255,0.06)',
  },
  backPatternLine: {
    height: 4,
    borderRadius: 2,
    backgroundColor: 'rgba(255,255,255,0.18)',
    borderWidth: 0,
  },
  cardFrontGradient: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 26,
    paddingBottom: 22,
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  raysContainer: {
    position: 'absolute',
    width: 400,
    height: 400,
    justifyContent: 'center',
    alignItems: 'center',
  },
  frontTextureLayer: {
    ...StyleSheet.absoluteFillObject,
  },
  frontTextureShape: {
    position: 'absolute',
    borderWidth: 1,
  },
  textureDash: {
    borderRadius: 3,
  },
  textureDot: {
    borderWidth: 0,
  },
  textureLine: {
    height: 2,
    borderWidth: 0,
    borderRadius: 1,
  },
  textureChip: {
    borderRadius: 6,
  },
  frontMaterialOverlay: {
    ...StyleSheet.absoluteFillObject,
  },
  frontMaterialOverlaySecondary: {
    ...StyleSheet.absoluteFillObject,
  },
  cardSheen: {
    position: 'absolute',
    top: -40,
    bottom: -40,
    width: 90,
    backgroundColor: 'rgba(255,255,255,0.75)',
    borderRadius: 45,
  },
  ray: {
    position: 'absolute',
    width: 3,
    height: 200,
    opacity: 0.12,
  },
  glowEffect: {
    position: 'absolute',
    width: 280,
    height: 280,
    borderRadius: 140,
    alignSelf: 'center',
    opacity: 0.5,
  },
  glowRing: {
    position: 'absolute',
    width: 320,
    height: 320,
    borderRadius: 160,
    borderWidth: 3,
    alignSelf: 'center',
  },
  imageContainer: {
    width: 248,
    height: 248,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
    zIndex: 10,
  },
  imageContent: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  coffeemonImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'contain',
  },
  sparkle: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    marginLeft: -10,
    marginTop: -10,
    zIndex: 5,
  },
  sparkleGlyph: {
    width: 14,
    height: 14,
    borderWidth: 2,
    borderRadius: 7,
  },
  sparkleGlyphDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    borderWidth: 0,
  },
  sparkleGlyphDiamond: {
    borderRadius: 2,
    transform: [{ rotate: '45deg' }],
  },
  sparkleGlyphRing: {
    backgroundColor: 'transparent',
  },
  infoShell: {
    alignItems: 'center',
    borderRadius: 18,
    width: '100%',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.58)',
    overflow: 'hidden',
    ...Platform.select({
      ios: {
        shadowColor: '#0f172a',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.38,
        shadowRadius: 16,
      },
      android: {
        elevation: 12,
      },
    }),
  },
  infoContainer: {
    width: '100%',
    padding: 1,
  },
  infoInner: {
    alignItems: 'center',
    borderRadius: 17,
    backgroundColor: 'rgba(250,252,255,0.9)',
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderWidth: 1,
    borderColor: 'rgba(148,163,184,0.35)',
  },
  typePill: {
    backgroundColor: 'rgba(226,232,240,0.9)',
    paddingHorizontal: 16,
    paddingVertical: 5,
    borderRadius: 14,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: 'rgba(148,163,184,0.42)',
  },
  typePillText: {
    color: '#334155',
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.8,
  },
  coffeemonName: {
    fontSize: 34,
    fontWeight: '800',
    color: '#0f172a',
    textAlign: 'center',
    marginBottom: 6,
    textShadowColor: 'rgba(255,255,255,0.6)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
    letterSpacing: 0.6,
  },
  congratsText: {
    fontSize: 14,
    color: '#334155',
    textAlign: 'center',
    fontWeight: '500',
    marginTop: 2,
    letterSpacing: 0.2,
    textShadowColor: 'rgba(255,255,255,0.5)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  rarityText: {
    fontSize: 20,
    color: '#FFD700',
    textAlign: 'center',
    fontWeight: '800',
    marginTop: 6,
    letterSpacing: 3.2,
    textShadowColor: 'rgba(255, 215, 0, 0.35)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 6,
    marginBottom: 2,
  },
  closeButton: {
    marginTop: 32,
    borderRadius: 30,
    overflow: 'hidden',
    minWidth: 200,
    ...Platform.select({
      ios: {
        shadowColor: '#4A90E2',
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.5,
        shadowRadius: 12,
      },
      android: {
        elevation: 12,
      },
    }),
  },
  closeButtonGradient: {
    paddingHorizontal: 60,
    paddingVertical: 18,
    borderRadius: 30,
  },
  closeButtonText: {
    color: '#FFFFFF',
    fontSize: 20,
    fontWeight: 'bold',
    textAlign: 'center',
    letterSpacing: 1,
  },
});
