import { StyleSheet } from 'react-native';

const pixelFont = {
  fontFamily: 'monospace',
  fontWeight: '700' as const,
  letterSpacing: 0.5,
};

export const hudStyles = StyleSheet.create({
  card: {
    width: 200,
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    borderRadius: 16,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.9)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 8,
  },
  cardPlayer: {
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
  },
  trainerTag: {
    position: 'absolute',
    top: -24,
    zIndex: 10,
  },
  trainerTagLeft: {
    left: 0,
  },
  trainerTagRight: {
    right: 0,
  },
  trainerTagInner: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 4,
    backgroundColor: 'rgba(156, 163, 175, 0.95)',
    borderRadius: 12,
    gap: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.15,
    shadowRadius: 3,
    elevation: 3,
  },
  trainerTagPlayer: {
    backgroundColor: 'rgba(16, 185, 129, 0.95)',
  },
  trainerIcon: {
    fontSize: 10,
    color: '#FFFFFF',
  },
  trainerTagText: {
    ...pixelFont,
    fontSize: 10,
    color: '#FFFFFF',
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  trainerTagTextPlayer: {
    fontWeight: '800',
  },
  topSection: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 10,
    position: 'relative',
    minHeight: 40,
  },
  typeBackground: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    right: 0,
    opacity: 0.08,
  },
  typePattern: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    width: 4,
    opacity: 0.4,
  },
  nameGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    zIndex: 1,
    flex: 1,
    gap: 6,
  },
  typeIconImage: {
    width: 40,
    height: 40,
    marginLeft: -10,
    marginRight: -10,
    marginTop: -10,
    marginBottom: -10,
  },
  typeIcon: {
    fontSize: 14,
    lineHeight: 18,
  },
  name: {
    ...pixelFont,
    fontSize: 13,
    color: '#1f2937',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    fontWeight: '800',
  },
  levelGroup: {
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: 2,
    zIndex: 1,
  },
  levelLabel: {
    ...pixelFont,
    fontSize: 10,
    color: '#f59e0b',
    fontWeight: '800',
  },
  levelValue: {
    ...pixelFont,
    fontSize: 15,
    color: '#f59e0b',
    fontWeight: '800',
  },
  barSection: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 6,
    backgroundColor: 'rgba(249, 250, 251, 0.8)',
  },
  hpLabelText: {
    ...pixelFont,
    fontSize: 10,
    color: '#6b7280',
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  barTrough: {
    flex: 1,
    height: 18,
    backgroundColor: '#e5e7eb',
    borderRadius: 12,
    overflow: 'hidden',
    position: 'relative',
    justifyContent: 'center',
  },
  barFill: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    borderRadius: 12,
  },
  hpTextContainer: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
    zIndex: 10,
  },
  hpNumber: {
    ...pixelFont,
    fontSize: 10,
    color: '#374151',
    fontWeight: '800',
    letterSpacing: 0.3,
    textShadowColor: 'rgba(255,255,255,0.9)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  typePatternInner: {
    display: 'none',
  },
});
