import { StyleSheet } from 'react-native';

const pixelFont = {
  fontFamily: 'monospace',
  fontWeight: '700' as const,
  letterSpacing: 1,
};

export const hudStyles = StyleSheet.create({
  card: {
    width: 220,
    backgroundColor: '#ffffff',
    borderWidth: 3,
    borderColor: '#000000',
    borderRadius: 18,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 3, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 8,
  },
  topSection: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 6,
    position: 'relative',
  },
  typeBackground: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    width: 80,
    opacity: 0.15,
  },
  typePattern: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    width: 6,
  },
  nameGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    zIndex: 1,
  },
  typePatternInner: {
    display: 'none',
  },
  typeIcon: {
    display: 'none',
  },
  name: {
    ...pixelFont,
    fontSize: 12,
    color: '#2a2a2a',
    textTransform: 'uppercase',
    letterSpacing: 0.3,
  },
  levelGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
    zIndex: 1,
  },
  levelLabel: {
    ...pixelFont,
    fontSize: 9,
    color: '#f59e0b',
    fontWeight: 'bold',
  },
  levelValue: {
    ...pixelFont,
    fontSize: 12,
    color: '#f59e0b',
    fontWeight: 'bold',
  },
  barSection: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 4,
    gap: 6,
    backgroundColor: '#f8f8f8',
  },
  hpLabel: {
    ...pixelFont,
    fontSize: 11,
    color: '#ffffff',
    backgroundColor: '#f59e0b',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 3,
    fontWeight: 'bold',
    minWidth: 28,
    textAlign: 'center',
  },
  barTrough: {
    flex: 1,
    height: 8,
    backgroundColor: '#e0e0e0',
    borderRadius: 8,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.1)',
  },
  barFill: {
    height: '100%',
    borderRadius: 8,
  },
  bottomSection: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
    paddingVertical: 4,
    backgroundColor: '#3f4652',
  },
  hpNumbers: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  hpNumber: {
    ...pixelFont,
    fontSize: 14,
    color: '#ffffff',
    fontWeight: 'bold',
    letterSpacing: 0.5,
  },
});
