import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.85)",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  container: {
    width: "100%",
    maxWidth: 500,
    maxHeight: "90%",
    borderRadius: 20,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.5,
    shadowRadius: 20,
    elevation: 10,
  },
  gradient: {
    padding: 20,
    borderRadius: 20,
  },
  header: {
    alignItems: "center",
    marginBottom: 20,
    paddingBottom: 15,
    borderBottomWidth: 2,
    borderBottomColor: "rgba(255, 255, 255, 0.3)",
  },
  emoji: {
    fontSize: 64,
    marginBottom: 10,
  },
  title: {
    fontSize: 36,
    fontWeight: "bold",
    color: "#FFFFFF",
    textShadowColor: "rgba(0, 0, 0, 0.5)",
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 4,
    marginBottom: 5,
  },
  subtitle: {
    fontSize: 18,
    color: "#FFFFFFCC",
    fontWeight: "600",
  },
  scrollView: {
    maxHeight: 400,
  },
  rewardsContainer: {
    gap: 15,
  },
  rewardSection: {
    backgroundColor: "rgba(255, 255, 255, 0.15)",
    borderRadius: 12,
    padding: 15,
    gap: 10,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#FFFFFF",
    marginBottom: 5,
    textShadowColor: "rgba(0, 0, 0, 0.3)",
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  rewardRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  rewardIcon: {
    fontSize: 24,
  },
  rewardText: {
    fontSize: 18,
    fontWeight: "600",
    color: "#FFFFFF",
  },
  levelUpSection: {
    backgroundColor: "rgba(255, 215, 0, 0.2)",
    borderRadius: 12,
    padding: 15,
    borderWidth: 2,
    borderColor: "rgba(255, 215, 0, 0.5)",
  },
  levelUpBadge: {
    alignItems: "center",
    gap: 5,
  },
  levelUpIcon: {
    fontSize: 40,
  },
  levelUpTitle: {
    fontSize: 22,
    fontWeight: "bold",
    color: "#FFFFFF",
    textShadowColor: "rgba(0, 0, 0, 0.3)",
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  levelUpLevel: {
    fontSize: 28,
    fontWeight: "bold",
    color: "#FFD700",
    textShadowColor: "rgba(0, 0, 0, 0.5)",
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 3,
  },
  coffeemonSection: {
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 12,
    padding: 15,
    gap: 10,
  },
  coffeemonCard: {
    backgroundColor: "rgba(255, 255, 255, 0.15)",
    borderRadius: 10,
    padding: 12,
    gap: 8,
    borderLeftWidth: 4,
    borderLeftColor: "#4CAF50",
  },
  coffeemonName: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#FFFFFF",
    marginBottom: 5,
  },
  coffeemonLevelUp: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "rgba(76, 175, 80, 0.2)",
    padding: 8,
    borderRadius: 8,
  },
  coffeemonLevelUpIcon: {
    fontSize: 20,
  },
  coffeemonLevelUpText: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#FFFFFF",
  },
  coffeemonExpText: {
    fontSize: 14,
    color: "#FFFFFFBB",
    fontStyle: "italic",
  },
  learnedMovesContainer: {
    backgroundColor: "rgba(33, 150, 243, 0.2)",
    padding: 10,
    borderRadius: 8,
    gap: 5,
  },
  learnedMovesTitle: {
    fontSize: 15,
    fontWeight: "bold",
    color: "#FFFFFF",
    marginBottom: 5,
  },
  learnedMoveText: {
    fontSize: 14,
    color: "#FFFFFF",
    paddingLeft: 10,
  },
  closeButton: {
    backgroundColor: "rgba(255, 255, 255, 0.25)",
    paddingVertical: 15,
    paddingHorizontal: 30,
    borderRadius: 12,
    marginTop: 20,
    alignItems: "center",
    borderWidth: 2,
    borderColor: "rgba(255, 255, 255, 0.4)",
  },
  closeButtonText: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#FFFFFF",
    textShadowColor: "rgba(0, 0, 0, 0.3)",
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
});
