version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: coffeemon-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass CofFeR3d1s
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "CofFeR3d1s", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

volumes:
  redis_data:
    driver: local
