import { StyleSheet } from 'react-native';
import { pixelArt } from '../../theme/pixelArt';

export const styles = StyleSheet.create({
  container: {
    backgroundColor: '#fff2c2',
    borderRadius: pixelArt.borders.radiusMedium,
    borderWidth: 4,
    borderTopWidth: 4,
    borderLeftWidth: 4,
    borderTopColor: '#faf8f0',
    borderLeftColor: '#faf8f0',
    borderBottomWidth: 4,
    borderRightWidth: 4,
    borderBottomColor: '#8B7355',
    borderRightColor: '#8B7355',
    padding: pixelArt.spacing.sm,
    marginHorizontal: pixelArt.spacing.md,
    marginTop: pixelArt.spacing.sm + pixelArt.spacing.xxl * 2,
    ...pixelArt.shadows.small,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: pixelArt.spacing.xs,
  },
  avatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: '#8B7355',
    marginRight: pixelArt.spacing.sm,
    backgroundColor: '#654321',
  },
  playerName: {
    fontSize: pixelArt.typography.pixelTitle.fontSize,
    color: '#8B7355',
    fontFamily: 'PressStart2P_400Regular',
    fontWeight: 'bold',
  },
  statsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  statusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: pixelArt.spacing.sm,
  },
  statusItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  progressBar: {
    width: 80,
    height: 20,
    backgroundColor: '#e8d890',
    borderRadius: pixelArt.borders.radiusSmall,
    marginLeft: pixelArt.spacing.sm,
    overflow: 'hidden',
    borderWidth: 4,
    borderColor: '#8B7355',
    shadowOffset: { width: -2, height: -2 },
    shadowOpacity: 0.4,
    shadowRadius: 0,
    shadowColor: '#808080',
    elevation: 1,
  },
  progressFill: {
    height: '100%',
    backgroundColor: '#00FF00',
    borderRadius: pixelArt.borders.radiusSmall,
    borderWidth: 1,
    borderColor: '#32CD32',
  },
  labelContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  icon: {
    width: 32,
    height: 32,
    marginRight: pixelArt.spacing.sm,
  },
  label: {
    fontSize: pixelArt.typography.pixelSubtitle.fontSize,
    color: '#8B7355',
    fontFamily: pixelArt.typography.pixelBody.fontFamily,
  },
  value: {
    fontSize: pixelArt.typography.pixelTitle.fontSize,
    color: '#8B7355',
    fontFamily: 'PressStart2P_400Regular',
    fontWeight: 'bold',
  },
  loadingText: {
    fontSize: pixelArt.typography.pixelBody.fontSize,
    color: '#8B7355',
    textAlign: 'center',
    fontFamily: pixelArt.typography.pixelBody.fontFamily,
  },
  errorText: {
    fontSize: pixelArt.typography.pixelBody.fontSize,
    color: pixelArt.colors.error,
    textAlign: 'center',
    fontFamily: pixelArt.typography.pixelBody.fontFamily,
  },
});